const personajes = [
    {
        "id" : 1,
        "name" : "Alain",
        "country" : "Azaleia",
        "desc" : "Crown prince of the fallen kingdom of Cornia, and son of its queen, Ilenia. After losing his mother at a young age amidst Cornian general Valmore's rebellion, he was ushered to the island of Palevia by the knight Josef, who taught him sword and strategy alike until the age of 17.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/alain_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/alain.png",

    },
    {
        "id" : 2,
        "name" : "Scarlett",
        "country" : "Azaleia",
        "desc" : "A priestess of the Palevian Orthodoxy who, after training tirelessly from a young age, now tends to the cathedral on the island of Palevia. In the end, she opts to leave the island and join Alain on his journey.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/scarlett_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/scarlett.png",
    },
    {
        "id" : 3,
        "name" : "Lex",
        "country" : "Azaleia",
        "desc" : "A childhood friend of Alain's, born on the island of Palevia to a local fisherman. After studying under Josef, he resolves to join the quest to liberate Fevrith.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/lex_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/lex.png",
    },
    {
        "id" : 4,
        "name" : "Josef",
        "country" : "Azaleia",
        "desc" : "A holy knight of the fallen kingdom of Cornia, he fled to Palevia with Alain ten years ago at Ilenia's behest. He has made great strides toward forming the Liberation Army ever since.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/josef_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/josef.png",
    },
    {
        "id" : 5,
        "name" : "Ilenia",
        "country" : "Azaleia",
        "desc" : "The queen of Cornia who ruled with both a keen military mind and a steady hand. Upon realizing there was no quelling the tide of rebellion, she entrusted her son Alain to her loyal retainer, Josef.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/ilenia_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/ilenia.png",
    },
    {
        "id" : 6,
        "name" : "Chloe",
        "country" : "Azaleia",
        "desc" : "Daughter of a friend of Josef. When she joined the Liberation Army, she became Josef's apprentice and studied martial arts and academics. While she maintains a courteous attitude toward Alain as her prince, she also counts herself as one of his good friends.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/chloe_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/chloe.png",
    },
    {
        "id" : 7,
        "name" : "Hodrick",
        "country" : "Azaleia",
        "desc" : "Former knight of Cornia. Trusted by Queen Ilenia, he served as her personal guard. During the rebellion, he fought alongside Ilenia, but ultimately he was defeated and captured by Valmore.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/hodrick_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/hodrick.png",
    },
    {
        "id" : 8,
        "name" : "Clive",
        "country" : "Azaleia",
        "desc" : "A member of the knights of the old kingdom of Cornia. Knighted early in his career, he has been praised for his intelligence and bravery since he was a squire. He has used his talents to lay the groundwork for the Liberation Army as Josef's right-hand man.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/clive_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/clive.png",
    },
    {
        "id" : 9,
        "name" : "Travis",
        "country" : "Azaleia",
        "desc" : "A spy who works for the Cornian Liberation Army. He's been in this clandestine line of work for years, but when the Liberation Army is formed, he joins the combat troops under Alain's command.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/travis_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/travis.png",
    },
    {
        "id" : 10,
        "name" : "Yahna",
        "country" : "Azaleia",
        "desc" : "A young witch living in the swamps of the Witches' village. When the Zenoiran army raids the village and begins to take the witches into captivity, she successfully escapes via a spell of feline transmutation.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/yahna_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/yahna.png",
    },
    {
        "id" : 11,
        "name" : "Melisandre",
        "country" : "Azaleia",
        "desc" : "The head of House Meillet, a distinguished Cornian clan. Losing her parents and older brother to illness early in life, she was raised and trained by her aunt and uncle as the heir to the Meillet family.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/melisandre_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/melisandre.png",
    },
    {
        "id" : 12,
        "name" : "Gilbert",
        "country" : "Azaleia",
        "desc" : "The crown prince of Drakenhold. Stepping into the shoes of his father the king, slain fighting the Zenoiran army, Gilbert is secretly amassing a force with the aim of restoring the kingdom.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/gilbert_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/gilbert.png",
    },
    {
        "id" : 13,
        "name" : "Virginia",
        "country" : "Azaleia",
        "desc" : "A survivor of the Cornian royal family. Niece of Queen Ilenia and older cousin of Alain. When Cornia fell, she fled to Drakenhold.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/virginia_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/virginia.png",
    },
    {
        "id" : 14,
        "name" : "Berengaria",
        "country" : "Azaleia",
        "desc" : "Former leader of the Tricorn Mercenaries. Widely feared as a deadly warrior, Berengaria established her own band of mercenaries and quickly grew it into a powerful force—until the day she abruptly disbanded the group and disappeared.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/berengaria_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/berengaria.png",
    },
    {
        "id" : 15,
        "name" : "Aramis",
        "country" : "Azaleia",
        "desc" : "A mercenary from Drakenhold hired by the Zenoira army. While his speech and affect is more elegant than might be expected, no one can deny his skill with the blade.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/aramis_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/aramis.png",
    },
    {
        "id" : 16,
        "name" : "Galerius",
        "country" : "Azaleia",
        "desc" : "Emperor of the reborn Zenoiran Empire, and once a renowned Cornian general by the name of Valmore. After leading a successful rebellion against the Cornian family, he claimed all of the Fevrith as his own.",
        "img" : "https://unicornoverlord.atlus.com/media/img/character/galerius_thumb.png",
        "imgFull": "https://unicornoverlord.atlus.com/media/img/character/galerius.png",
    },
    
];

module.exports = {
    personajes
};